### ISSUE TITLE
Timeout during ./stack.sh

### ISSUE THREAD

**Issue by lkatalin** [CCI-MOC/more#12]
![screenshot from 2018-06-28 15-40-20](https://user-images.githubusercontent.com/22075926/42056884-a550b4de-7ae9-11e8-812a-1484f22dfcb0.png)

A timeout occurred when `./stack.sh` was on command `sudo systemctl start devstack@etcd.service`.

Error message: `Job for devstack@etcd.service failed because a timeout was exceeded. See "systemctl status devstack@etcd.service" and "journalctl -xe" for details.`
Then it gave `exit 1`.

The output of `journalctl -xe` is attached.

[journalctl.txt](https://github.com/CCI-MOC/ORE/files/2146766/journalctl.txt)

**Comment by HuzefaMandvi** [comment]
Was this on a clean VM or had you run stack.sh before? Also, was this before or after you switched to a larger VM flavor?

**Comment by lkatalin** [comment]
This built successfully the following time I tried, and I suspect it may have been a network issue unrelated to ORE.

**Comment by HuzefaMandvi** [comment]
Okay, I'm closing this issue for now. LMK if you ever get a similar problem and we can reopen and investigate.
