### ISSUE TITLE
No "neutron" shows up in network-related traces

### ISSUE THREAD

**Issue by lkatalin** [CCI-MOC/more#14]
But is neutron even instrumented?

**Comment by HuzefaMandvi** [comment]
I just got neutron to show up in a trace with openstack server create. Basically, there were some important bugfixes in the stable/queens version of osprofiler. These steps appear to resolve #6 and hopefully can resolve this.

Steps to reproduce:

1. Install the two patches[1][2]
2. After installing each patch, run `sudo pip install --no-deps --force-reinstall -U .` in /opt/stack/nova and /opt/stack/neutron
3. In /opt/stack/osprofiler, run `git checkout stable/queens`
4. Reinstall osprofiler by running `sudo pip install --no-deps --force-reinstall -U .` in /opt/stack/osprofiler
5. Restart openstack services: `sudo systemctl restart devstack@*`
6. Try osprofiler commands

LMK if that works (or, more likely, gives us some new error message)

**Comment by lkatalin** [comment]
Great! I just followed your steps and got a trace for `server create` that includes neutron, nova, glance, and keystone. No cinder, but I think that may be normal. Will continue experimenting.
