### ISSUE TITLE
stack.sh not using branches specified in local.conf for plugins

### ISSUE THREAD

**Issue by HuzefaMandvi** [CCI-MOC/more#15]
I specified stable/queens for osprofiler in local.conf, but after stack.sh completed I had the stable/pike version of osprofiler

**Comment by EmreAtes** [comment]
This could be due to stackrc line 495 and 496. I changed them before to fix something else.
See https://github.com/openstack-dev/devstack/blob/stable/pike/stackrc#L494

**Comment by HuzefaMandvi** [comment]
If the branch is specified as 

$SERVICE_BRANCH=

then it will work as expected.
