### ISSUE TITLE
Migration to docc-lab?

### ISSUE THREAD

**Issue by EmreAtes** [CCI-MOC/more#19]
Should we move this repo into docc-lab? (Raja's organization)

**Comment by HuzefaMandvi** [comment]
Pinging Raja on this

**Comment by lkatalin** [comment]
To-do: Fork the ORE into docc-lab.

**Comment by EmreAtes** [comment]
see https://github.com/docc-lab/ORE - pull requests and issues will still be here unless they specifically relate to our system?

**Comment by HuzefaMandvi** [comment]
Yeah that sounds good. General/infrastructure/etc fixes to ORE can live in CCI-MOC, and specific monitoring fixes can live in docc-lab.
