### ISSUE TITLE
OSProfiler patch doesn't work

### ISSUE THREAD

**Issue by EmreAtes** [CCI-MOC/more#22]
Pull request #16 doesn't fix the issue, after a fresh VM creation, the OSprofiler version installed is still 1.11, not `stable/queens`, even though `/opt/stack/osprofiler` is queens.

Doing `sudo pip install` in `/opt/stack/osprofiler` (without anything else), and then restarting services fixes this issue.

**Comment by HuzefaMandvi** [comment]
This probably results from commit 34a8f1e60310b5cb2364767712083ef838e384b0 where I tried to clean up the osprofiler fix by just specifying the branch. Looking into it now, will probably just have to revert that commit.
